// <auto-generated />
using System;
using Mavim.Manager.ChangelogTitle.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mavim.Manager.ChangelogTitle.DbContext.Migrations
{
    [DbContext(typeof(TitleDbContext))]
    [Migration("20200924093105_Add datalanguage")]
    partial class Adddatalanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mavim.Manager.ChangelogTitle.DbModel.Title", b =>
                {
                    b.Property<int>("ChangelogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReviewerUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataLanguage")
                        .HasColumnType("int");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromTitleValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatorUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TimestampApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToTitleValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicDcv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangelogId");

                    b.ToTable("Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
