// <auto-generated />

using Mavim.Manager.MavimDatabaseInfo.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Mavim.Manager.Catalog.EFCore.Migrations
{
    [DbContext(typeof(MavimDatabaseInfoDbContext))]
    [Migration("20190424095840_InitialState")]
    partial class InitialState
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mavim.Manager.Api.MavimDatabaseInfo.EFCore.Models.MavimDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    
                    b.Property<string>("ConnectionProvider")
                        .IsRequired();

                    b.Property<string>("ConnectionProviderType")
                        .IsRequired();

                    b.Property<string>("ConnectionString")
                        .IsRequired();

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<string>("Schema");

                    b.HasKey("Id");

                    b.ToTable("MavimDatabases");
                });
#pragma warning restore 612, 618
        }
    }
}
