version: "3.4"

services:
  mavim.apidatabaseinfo.linux.img:
    image: ${DOCKER_REGISTRY-}mavimapidatabaseinfo.linux.img
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 5022:8080
    expose:
      - 8080
    build:
      context: ../../
      dockerfile: Mavim-services/MavimDatabaseInfo/Mavim.Manager.Api.MavimDatabaseInfo/Dockerfile
