version: "3.4"

services:
  mavim.apiaclogrelation.linux.img:
    image: ${DOCKER_REGISTRY-}mavimapiclogrelation.linux.img
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 5020:8080
    expose:
      - 8080
    build:
      context: ../../
      dockerfile: Mavim-services/Changelog/Relationship/Int/Mavim.Manager.Api.Int.ChLog.Relationship/Dockerfile
