version: "3.4"

services:
  mavim.cltitlepublic.linux.img:
    image: ${DOCKER_REGISTRY-}mavimapicltitlepublic.linux.img
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 5014:8080
    expose:
      - 8080
    build:
      context: ../../
      dockerfile: Mavim-services/Changelog/Title/Ext/Mavim.Manager.Api.ChangelogTitle.Public/Dockerfile
