version: "3.4"

services:
  mavim.apiwopihost.linux.img:
    image: ${DOCKER_REGISTRY-}mavimapiwopihost.linux.img
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 5004:8080
    expose:
      - 8080
    build:
      context: ../../
      dockerfile: Mavim-services/Wopi/Mavim.Manager.Api.WopiHost/Dockerfile
