// <auto-generated />

using System;
using Mavim.Manager.Connect.Write.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Mavim.Manager.Connect.Write.Migrations
{
    [DbContext(typeof(ConnectDbContext))]
    internal class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Mavim.Manager.Connect.Write.Database.Models.EventSourcingModel", b =>
            {
                b.Property<Guid>("EntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AggregateId")
                    .HasColumnType("int");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("EntityModelVersion")
                    .HasColumnType("int");

                b.Property<int>("EntityType")
                    .HasColumnType("int");

                b.Property<int>("EventType")
                    .HasColumnType("int");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("datetime2");

                b.HasKey("EntityId", "AggregateId");

                b.HasIndex("CompanyId");

                b.ToTable("EventSourcings");
            });
#pragma warning restore 612, 618
        }
    }
}